Add Sriram to CAPI reviewers
cloudfoundry/community pull request #1018
Opened 2024-11-13 17:40 UTC by gururajsh

Sriram is a devex team memeber who works on CAPI. Need to add him as a reviewer.

2024-11-13 21:57 UTC, Gerg requested changes
In order to be a WG Reviewer, you need to be a CFF Contributor (basically, you need to be in [contributors.yml](https://github.com/cloudfoundry/community/blob/main/org/contributors.yml)).

The Contributor and Reviewer promotion process is described here: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-contributor

Feel free to add their Contributor promotion into this PR.

2024-11-18 14:13 UTC, gururajsh commented
> In order to be a WG Reviewer, you need to be a CFF Contributor (basically, you need to be in [contributors.yml](https://github.com/cloudfoundry/community/blob/main/org/contributors.yml)).
> 
> The Contributor and Reviewer promotion process is described here: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-contributor
> 
> Feel free to add their Contributor promotion into this PR.

Added him as a contributor

2024-11-19 19:50 UTC, Gerg approved these changes

2024-11-19 20:29 UTC, xandroc approved these changes
lgtm!

2024-11-19 20:29 UTC, a-b approved these changes
LGTM

2024-11-19 20:32 UTC, sethboyles approved these changes

2024-11-19 20:56 UTC, merged