Add go-cf-api POC repos
cloudfoundry/community pull request #182
Opened 2021-12-08 16:32 UTC by stephanme

Proposal doc (problem statement and different solution proposals):
https://docs.google.com/document/d/1DTYjYcQy0fzJlf7VvfWikTLnPm_kp9BCp8v-Xiw-Wk0/edit?usp=sharing

2022-03-22 14:19 UTC, stephanme commented
The repos contains a POC. We want to keep them (at least) as a reference for performance and load tests.
This PR adds them to the CAPI area. An alternative would be a separate CAPI-POC area.

The repos started in cloudfoundry-incubator, moved then to cloudfoundry and are now part of the [Cloudfoundry Orphaned list](https://docs.google.com/spreadsheets/d/1uCRQwauqsGUDmbR16JfKlxgcVv3IpS5TRuYKQjRfWa4/edit#gid=0).

2022-04-19 12:15 UTC, stephanme commented
@Gerg and @sethboyles : Any opinion if and how to add the POC repos to the WG?

There is meanwhile an [RFC proposal](https://github.com/cloudfoundry/community/pull/251) on mgmt of repo ownership. The two POC repos belong to the subset of active, unmanaged repos. Active in the sense they are not archived, not in the sense that they are under active development.
As mentioned, we (capi approvers and contributors from SAP) want to keep them (at least) as a reference for performance and load tests until it is clear if the envisioned CAPI performance can be reached with Ruby (with suggested improvements like Ruby 3, Puma, incremental perf improvements, query optimization ...).

2022-04-19 23:53 UTC, Gerg commented
@sethboyles noticed that they are currently assigned to this WG in `cloudfoundry.yml`: https://github.com/cloudfoundry/community/blob/c4e233cc4bdccaff573c47752e942089ada6bfbe/org/cloudfoundry.yml#L2945-L2946

2022-04-20 23:00 UTC, Gerg requested changes
There are a number of unrelated whitespace changes. Consider committing those separate from this PR.

Otherwise, LGTM.

2022-04-21 11:27 UTC, stephanme commented
Removed the whitespace changes that got applied by my editor automatically.

2022-04-21 11:42 UTC, stephanme commented
Requested TOC review as per proposed [RFC: Process for repository ownership changes](https://github.com/cloudfoundry/community/pull/251).

2022-04-21 12:06 UTC, loewenstein approved these changes

2022-04-21 17:23 UTC, Gerg approved these changes

2022-04-21 17:28 UTC, emalm approved these changes

2022-05-03 07:23 UTC, LeePorte approved these changes

2022-05-03 14:51 UTC, merged