Fix url of community repo where to file a PR
cloudfoundry/community pull request #210
Opened 2022-02-21 10:19 UTC by stephanme

Link directly to https://github.com/cloudfoundry/community/blob/main/org/cloudfoundry.yml using an absolute url.

2022-02-21 10:28 UTC, LeePorte approved these changes

2022-02-22 15:21 UTC, emalm commented
I'm not sure we want the process that the RFC defines to be so tightly tied to the structure and location of the YAML files in the community repository: whenever that changes for technical reasons, then we'll have to keep updating this RFC with the new details.

2022-02-22 15:27 UTC, LeePorte commented
> I'm not sure we want the process that the RFC defines to be so tightly tied to the structure and location of the YAML files in the community repository: whenever that changes for technical reasons, then we'll have to keep updating this RFC with the new details.

That's a valid point. I guess it's a balance between user friendliness and frequency of updating.

2022-02-22 15:56 UTC, loewenstein approved these changes

2022-02-22 16:16 UTC, emalm requested changes
I think it'll be clearer if we link to the PR list for the community repo and then have a separate link to the existing YAML file with the org structure.

2022-02-22 16:16 UTC, emalm commented on toc/rfc/rfc-0002-github-members.md
>  This PR should add the member directly to the YAML file describing the organization membership, as automation will synchronize the GitHub org membership with the contents of this file periodically.
```suggestion
A Working Group approver or lead should raise a [PR on the community repository](https://github.com/cloudfoundry/community/pulls) to propose adding a new member to the `cloudfoundry` GitHub org.
This PR should add the member directly to the [YAML file describing the organization membership](https://github.com/cloudfoundry/community/blob/main/org/cloudfoundry.yml), as automation will synchronize the GitHub org membership with the contents of this file periodically. 
```

2022-03-01 15:34 UTC, merged