Add cf-test-helpers to org automation
cloudfoundry/community pull request #233
Opened 2022-03-25 18:49 UTC by ctlong

* Add it to the list of cloudfoundry repos
* Give ARD WG members relevant permissions

2022-03-25 22:18 UTC, davewalter approved these changes

2022-03-29 13:42 UTC, stephanme requested changes
cf-test-helpers should be added to https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-deployments.md in addition.

2022-03-30 06:17 UTC, stephanme approved these changes

2022-04-05 14:47 UTC, loewenstein approved these changes

2022-04-05 17:19 UTC, jochenehret approved these changes

2022-04-06 07:27 UTC, LeePorte approved these changes

2022-04-12 14:43 UTC, merged