Autoscaler WG: add Marcin Kubica
cloudfoundry/community pull request #306
Opened 2022-06-13 09:44 UTC by marcinkubica

Add Marcin Kubica (work for SAP)

2022-06-22 12:04 UTC, silvestre requested changes

2022-06-22 12:04 UTC, silvestre commented on org/cloudfoundry.yml
>          members:
Unfortunately you do not yet meet the requirements for a maintainer as defined in https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#requirements-2 - Please add yourself to the `members` section

```suggestion
        members:
        - marcinkubica
```

2022-06-30 10:45 UTC, marcinkubica commented
Hi @Gerg are you ok to merge this one for me?
Cheers

2022-06-30 20:46 UTC, Gerg commented
Per https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0008-role-change-process.md#promotion-to-approver, you need 2 existing approvers to review your application and attest that you meet the criteria for the approver role. I see @silvestre already approved the promotion, so you will need one more.

Once that criteria is met, I'll merge this PR.

2022-07-01 08:10 UTC, asalan316 approved these changes
LGTM

2022-07-04 07:44 UTC, marcinkubica commented
@Gerg thanks, done.

2022-07-05 18:03 UTC, Gerg approved these changes

2022-07-05 18:06 UTC, merged