Generate github teams according to RFC-0005
cloudfoundry/community pull request #310
Opened 2022-06-15 11:40 UTC by stephanme

- teams for WG, WG areas, WG leads and WG bots
- added empty bot user list to all WG yamls
- enabled only for ARD and FI WGs as pilots

2022-06-15 13:00 UTC, rkoster requested changes
How will this script deal with repos outside the cloudfoundry org?

2022-06-15 16:45 UTC, stephanme commented on toc/working-groups/foundational-infrastructure.md
> +bots: []
The script should only deal with repos within the cloudfound org, isn't it? All CF repos got moved into the cloudfoundry org. But in the end, only peribolos deals with real github entities. The script just moves yaml around.

The validation failed on the team wg-app-runtime-deployments which is one of the 'to be created' teams. There is a log line that says
```
{"client":"github","component":"peribolos","file":"k8s.io/test-infra/prow/github/client.go:910","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"CreateTeam(cloudfoundry, {0 wg-app-runtime-deployments  Leads and approvers for App Runtime Deployments WG closed \u003cnil\u003e \u003cnil\u003e })","severity":"info","time":"2022-06-15T13:45:36Z"}
```
but it later fails on listing the team members (no surprise - the team doesn't exist). I assume this is caused by the "--confirm=false" flag.

2022-06-15 18:51 UTC, rkoster commented on toc/working-groups/foundational-infrastructure.md
> +bots: []
in the foundational infrastructure working group there are several repos which have not been moved into the cloudfoundry org. For example the ones in the bosh-packages  and the bosh-io orgs. These should probably be filtered from the generated config.

2022-06-20 14:27 UTC, stephanme commented on toc/working-groups/foundational-infrastructure.md
> +bots: []
I missed this aspect of FI WG. Added a filter for cloudfoundry repos.

2022-06-21 12:22 UTC, jochenehret approved these changes

2022-06-21 14:03 UTC, rkoster commented on org/org_management.py
> +        repositories = {r for a in wg["areas"] for r in a["repositories"] if r.startswith("cloudfoundry/")}
We will have to rework this line later when we onboard other orgs into the automation but for now it should be fine.

2022-06-21 14:43 UTC, LeePorte approved these changes

2022-06-21 14:44 UTC, emalm approved these changes

2022-06-21 14:54 UTC, merged