[ARI] Update buildpacks team's repositories
cloudfoundry/community pull request #322
Opened 2022-06-28 00:30 UTC by Gerg

- Repositories copied from the Working Group charter yaml
- Permissions increased to admin

Related: https://github.com/cloudfoundry/community/pull/313#issuecomment-1164471705

2022-06-28 12:02 UTC, rkoster approved these changes

2022-06-28 14:39 UTC, dsboulder approved these changes

2022-06-28 14:54 UTC, dsboulder requested changes
Oops, we're supposed to use `write` not admin access for maintainers

2022-06-28 21:59 UTC, brayanhenao commented
@Gerg In addition to the permissions on the cflinxufs4 repositories, I noticed that the team members are not up to date. I put the actual ones in the issue #315

2022-06-30 14:57 UTC, emalm approved these changes

2022-06-30 15:17 UTC, stephanme approved these changes
I hope that we get #317 merged in next TOC meeting which enables github team automation for all WGs.
Then I suggest to compare this App Runtime Interfaces WG Buildpacks team with the generated team wg-app-runtime-interfaces-buildpacks (especially bots).

2022-07-05 14:42 UTC, merged