[RFC] Formally track aspiring approvers as reviewers
cloudfoundry/community pull request #333
Opened 2022-07-05 08:45 UTC by rkoster

Extend the working group yaml defenitions to optionally include a `reviewers` key with a list of contributors who like to become approvers.
The github org automation should use this information to create a github team for the area with `-reviewers` suffix and __read__ permissions.

This will later allow automatic assignment of PRs to be reviewed, which will help these contributors more easily statisfy the requirments to become approvers.

This PR formalizes the pattern introduced in: https://github.com/cloudfoundry/community/pull/324

2022-07-08 14:04 UTC, stephanme requested changes
We need to mention or extend toc/rfc/rfc-0008-role-change-process.md, i.e. how would a contributor gain reviewers role.

I guess the process will be similar as for promotion to contributor:
- pre-requisite: user is contributor and files a PR
- 2 existing approvers review the PR with +1
- WG lead will merge or close

2022-07-12 15:32 UTC, pivotal-marcela-campo commented
I do think it is useful to help contributors get approver status. It provides an standardised way of assigning reviews and following up on that within the PR to make sure the review gets done before merging.

2022-07-19 06:35 UTC, stephanme commented
A use case discussed in CAPI Open Office Hour: Reviewers role can also be used to grant read access to Concourse pipelines of a WG area that the team doesn't want to make publicly accessible (e.g. due to risk of revealing credentials in the build logs).

2022-07-19 06:39 UTC, stephanme commented
Q: Should reviewers be part of the team wg-[WORKING-GROUP-NAME]?

https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0005-github-teams-and-access.md as of today would exclude them (membership: All approvers and leads for a WG). The intended use case for the WG global team (for organization and tagging) suggests to add them. There are no repo permissions granted by this team.

2022-07-19 14:39 UTC, ameowlia commented
Yes, the ARP working group would like to have reviewer teams. This way I can automatically assign PRs to these teams.

2022-07-19 14:42 UTC, rkoster commented on toc/rfc/rfc-formal-aspiring-approvers-as-reviewers.md
> +Extend the working group yaml defenitions to optionally include a `reviewers` key with a list of contributors who like to become approvers.
I would go optionally since otherwise, we would have to update all other working groups, even the ones who won't use this feature.

2022-07-19 14:44 UTC, rkoster commented
> Q: Should reviewers be part of the team wg-[WORKING-GROUP-NAME]?
> 
> https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0005-github-teams-and-access.md as of today would exclude them (membership: All approvers and leads for a WG). The intended use case for the WG global team (for organization and tagging) suggests to add them. There are no repo permissions granted by this team.

2022-07-25 14:15 UTC, stephanme approved these changes

2022-07-26 14:57 UTC, emalm commented
TOC voted today to start the final comment period on this RFC, concluding August 2.

2022-08-02 14:45 UTC, merged