Add new CF for K8s area to CF on K8s WG
cloudfoundry/community pull request #358
Opened 2022-07-15 20:28 UTC by davewalter

Add missing CF for K8s repositories to the CF on K8s working group.

2022-07-15 20:50 UTC, emalm commented
If we're pulling in the cf-for-k8s repos for the time being until we retire them completely, should we have a new technical area for them that's separate from the existing "CF on K8s" one (which maybe we should also rename "Korifi" to match the new official project name)?

2022-07-15 21:28 UTC, davewalter commented
@emalm We updated the PR to incorporate your suggestions.

On a separate topic, is there a process for removing approvers who are no longer full-time contributors to a project? We noticed that Akira and Mario are still listed as approvers for Korifi.

2022-07-15 21:48 UTC, emalm commented
Thanks!

> is there a process for removing approvers who are no longer full-time contributors to a project?

Yep, https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#revoking-approver-role now represents the process that was approved in [RFC 0008](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0008-role-change-process.md).

2022-07-15 23:39 UTC, Birdrock approved these changes

2022-07-15 23:49 UTC, emalm requested changes
Minor change requested to exclude the archived CRD repository, but otherwise LGTM!

2022-07-15 23:49 UTC, emalm commented on toc/working-groups/cf-on-k8s.md
> +  - cloudfoundry/cf-crd-explorations
This repository is archived, so it shouldn't be under the ownership of any WG.
```suggestion
```

2022-07-19 15:20 UTC, emalm approved these changes

2022-07-19 15:21 UTC, stephanme approved these changes

2022-07-19 15:21 UTC, merged