Add Reviewer role to toc/ROLES.md
cloudfoundry/community pull request #394
Opened 2022-08-12 15:55 UTC by AP-Hunt

The reviewer role was defined in [RFC 12](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0012-formal-aspiring-approvers-as-reviewers.md), but had not been added to `ROLES.md`.

2022-08-16 13:06 UTC, stephanme requested changes
The new Reviewer role may add confusion to the Approver role requirement: Reviewer of the codebase for at least 3 months.

In the past, we meant that the approver candidate should be active for 3 months on the code base, prominently reviewing contributions.
Now you can read it as: The candidate must have Reviewer role for at least 3 months. I don't think that we should add this as requirement. If the candidate has the 20+ substantial contributions/reviews it doesn't matter if he/she was Reviewer or Contributor.

2022-08-16 13:06 UTC, stephanme commented on toc/ROLES.md
> +- Reviwing assigned PRs within the Working Group Area
typo: Reviewing

2022-08-16 13:06 UTC, stephanme commented on toc/ROLES.md
> +<i>Includes everything from [Reiviewer](#reviewer)</i>
typo: Reviewer

2022-08-16 14:52 UTC, rkoster approved these changes

2022-08-30 14:22 UTC, emalm approved these changes

2022-08-30 14:52 UTC, merged