add three reviewers to CredHub and UAA
cloudfoundry/community pull request #422
Opened 2022-09-23 01:40 UTC by swalchemist

* They are all members of the team at VMware that has been actively maintaining these repos.

2022-09-23 14:18 UTC, Tallicia commented
How can we assign a reviewer to this? @rkoster @bruce-ricard

2022-09-23 14:36 UTC, bruce-ricard approved these changes
They are our team members.

2022-09-23 16:30 UTC, peterhaochen47 approved these changes

2022-09-23 19:00 UTC, swalchemist commented
Note that Hongchol and I have been acting as reviewers and approvers under the old structure for more than 3 months, and Alicia for just a few weeks short of 3 months.

2022-09-26 23:46 UTC, peterhaochen47 commented
Hi @rkoster, could you take a look at this PR please?

2022-09-27 21:08 UTC, hsinn0 commented
My Justification of asking for the approver role:

As a member of TAS identity and Credential team, I have been maintaining and contributing for UAA and CredHub repo for more than year.  I have been involved in many reviewing/merging PRs, bug fixes and feature implementation.  Approver role is needed for me to continue performing the same kind of tasks.

For UAA, I was author or co-author of 19 commits in develop branch and much more in 74.5.x branch: 
- https://github.com/cloudfoundry/uaa/commits/develop?author=hsinn0
- https://github.com/cloudfoundry/uaa/commits/74.5.x?author=hsinn0

For CredHub, I was author or co-author of more than 20 commits:
- https://github.com/cloudfoundry/credhub/commits/main?author=hsinn0

2022-09-27 23:18 UTC, swalchemist commented
I have been contributing to UAA and CredHub since December 2021 with more than 50 commits. We have been making direct commits before we started requiring PRs for CloudFoundry repos. Also, note that many of these commits have been migrated from private LTS repos to the open source repos.

https://github.com/cloudfoundry/uaa/commits/develop?author=swalchemist
https://github.com/cloudfoundry/credhub/commits/main?author=swalchemist

2022-09-28 09:23 UTC, rkoster requested changes
I tried performing the same analysis for: @Tallicia
- https://github.com/cloudfoundry/uaa/commits/develop?author=Tallicia
- https://github.com/cloudfoundry/uaa/commits/74.5.x?author=Tallicia
- https://github.com/cloudfoundry/credhub/commits/main?author=Tallicia
I could not find any commits. This is fine, however, this would mean that a reviewer role would be more appropriate at this time.

2022-09-28 09:23 UTC, rkoster commented on toc/working-groups/foundational-infrastructure.md
> +    github: swalchemist
```suggestion
    github: swalchemist
  reviewers:
```

2022-09-28 09:23 UTC, rkoster commented on toc/working-groups/foundational-infrastructure.md
> +    github: swalchemist
```suggestion
    github: swalchemist
  reviewers:
```

2022-09-28 17:30 UTC, rkoster approved these changes

2022-09-29 12:41 UTC, beyhan approved these changes

2022-09-29 12:45 UTC, merged