Modify approvers for integrated-databases
cloudfoundry/community pull request #426
Opened 2022-09-26 21:59 UTC by colins

Remove 1 and add 5 approvers

The 5 new approvers are vmware employees

Co-authored-by: Colin Shield <cshield@vmware.com>
Co-authored-by: Andrew Garner <garnera@vmware.com>

2022-09-27 13:13 UTC, rkoster commented
@colins Could you update the PR with the required proof of contributions as outlined [here](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0006-approver-requirements.md).
A great example of this can be seen here: https://github.com/cloudfoundry/community/pull/368

2022-09-27 15:04 UTC, rkoster requested changes

2022-09-27 15:04 UTC, rkoster commented on toc/working-groups/foundational-infrastructure.md
> +  - name: Kim Basset
Based on the supplied contribution statistics Kevin and Ryan won't be eligible yet for approver status. They do however qualify for reviewer status. 

```suggestion
  - name: Kim Basset
  reviewers:
```

2022-09-27 16:18 UTC, rkoster approved these changes

2022-09-28 08:39 UTC, beyhan approved these changes

2022-09-28 08:41 UTC, merged