Fix the reference to contributing.md in WGs description
cloudfoundry/community pull request #497
Opened 2022-12-14 13:57 UTC by beyhan

2022-12-20 16:19 UTC, beyhan commented
I have updated the pr with what we have discussed in the TOC meeting today.

2023-01-02 07:18 UTC, rkoster requested changes

2023-01-02 07:18 UTC, rkoster commented on toc/working-groups/WORKING-GROUPS.md
> +around this at the momentso and would fall back to a general decision by the TOC to accept or remove a proposed charter document for a WG.
Typo in moment

2023-01-02 15:43 UTC, beyhan commented on toc/working-groups/WORKING-GROUPS.md
> +around this at the momentso and would fall back to a general decision by the TOC to accept or remove a proposed charter document for a WG.
Thanks I fixed the type.

2023-01-02 17:15 UTC, rkoster approved these changes

2023-01-03 14:52 UTC, stephanme approved these changes

2023-01-10 00:50 UTC, emalm approved these changes

2023-01-10 10:55 UTC, AP-Hunt approved these changes

2023-01-10 15:46 UTC, merged