Promote Joseph Palermo to Tech Lead in the FI working group
cloudfoundry/community pull request #519
Opened 2023-01-26 14:07 UTC by rkoster

Through this PR I would like to promote @jpalermo to Tech Lead in the Foundation Infrastructure working group.
The screenshot below proves Joseph has been involved in the [required number of reviews](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#working-group-technical-lead).
<img width="1326" alt="Screenshot 2023-01-26 at 14 52 37" src="https://user-images.githubusercontent.com/380697/214852941-3d047104-4bec-41e4-9603-3392a7ff7ce9.png">
[source](https://insights.lfx.linuxfoundation.org)

Joseph has been active in the Cloud Foundry github org for [10 years now](https://github.com/jpalermo?tab=overview&from=2013-12-01&to=2013-12-31&org=cloudfoundry), and made his [first contribution to bosh in 2014](https://github.com/cloudfoundry/bosh/commit/fa7edcf46f385cbf0debae34310d842f05a6ce0d).

cc @beyhan

2023-01-26 14:08 UTC, rkoster commented
PR needs @cloudfoundry/toc approval as per: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#working-group-technical-lead

2023-01-27 13:01 UTC, beyhan approved these changes

2023-01-31 00:31 UTC, emalm requested changes
I suggested removing Palermo from the BOSH area as well, but otherwise LGTM!

2023-01-31 00:31 UTC, emalm commented on toc/working-groups/foundational-infrastructure.md
> -    github: jpalermo
Should this PR also remove Palermo from the BOSH area for consistency?

2023-01-31 13:46 UTC, stephanme approved these changes

2023-01-31 15:45 UTC, emalm approved these changes

2023-01-31 15:45 UTC, AP-Hunt approved these changes

2023-01-31 15:45 UTC, stephanme approved these changes

2023-01-31 15:45 UTC, merged