Request for Kelly OHara to be docs approver
cloudfoundry/community pull request #555
Opened 2023-03-08 22:33 UTC by kohara88

I am a new docs writer from VMWare and am requesting to become an approver for all docs areas.
This affects 3 working groups and requires approval from the tech leads in each working group:
* App Runtime Platform - @ameowlia 
* App Runtime Interfaces - @Gerg 
*  Foundational Infrastructure - @beyhan and/or @rkoster

2023-03-08 22:50 UTC, ameowlia requested changes
Hi @kohara88 , It looks like you added yourself to the wrong areas in the 3 working groups. You'll want to add yourself to the Docs area for the 3 working groups and you'll want to be an approver (not a reviewer). Look where "Anita Flegg" is in those 3 files, and that is the correct place to add yourself.

2023-03-09 15:01 UTC, ameowlia approved these changes

2023-03-09 15:01 UTC, ameowlia commented
Changes look good. One the other WG leads approver, then we can merge.

2023-03-09 15:22 UTC, Gerg approved these changes

2023-03-14 14:08 UTC, beyhan approved these changes

2023-03-14 14:12 UTC, merged