Add routing-ci repository
cloudfoundry/community pull request #587
Opened 2023-04-21 12:12 UTC by plowin

Hi @ameowlia, as discussed in our last WG meeting, we would like to create a new repo for "routing-ci", similar to e.g. "runtime-ci". It seems this repo existed in the past and I am not sure if we could revive it like this. I am also fine with moving it to the `Networking-Extensions` ~line 363 if you prefer.

We will probably not store the CI pipelines in this repo as they better stay close with the respective repo they are used in. But we would create/host the VM running these pipeline in this repo. Please review/add your thoughts.

2023-06-26 14:37 UTC, ameowlia requested changes
@plowin Unless you want to unarchive routing-ci and use the contents in it, can you come up with a new name for the repo?

2023-06-26 14:45 UTC, plowin commented
Thanks for the pointer!
I missed that this repo still exists, proposed a new name, @ameowlia

2023-06-27 22:06 UTC, ameowlia approved these changes
🎉

2023-06-27 22:07 UTC, merged

2024-06-21 09:11 UTC, plowin commented
In the next weeks we are prioritizing bringing a concourse for ARP WG up in this repo