Archive resolvconf-manager projects
cloudfoundry/community pull request #643
Opened 2023-07-10 17:06 UTC by ystros

When developing the Bionic stemcell, the team originally planned to introduce a wrapper around managing resolv.conf within the agent and BOSH DNS. However, this work was reverted (likely due to backward compatibility concerns) and abandoned. This idea was not incorporated at all into the Jammy stemcells.

As such, we should not continue actively maintaining the associated repositories.

Original implementation story:
https://www.pivotaltracker.com/story/show/167763426

Revert: 
https://www.pivotaltracker.com/n/projects/2238419/stories/168790375 
https://github.com/cloudfoundry/bosh-dns-release/commit/aac14421fd63aa7e266f93cf16d614ec6fce60d4

2023-07-18 14:01 UTC, rkoster requested changes
Could you also remove both repos from the foundational infrastructure working group charter: https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md?

2023-07-19 16:20 UTC, ystros commented
Good catch. Updated!

2023-07-19 19:16 UTC, rkoster approved these changes

2023-07-20 11:13 UTC, beyhan approved these changes

2023-07-25 12:26 UTC, stephanme approved these changes

2023-07-25 14:43 UTC, ameowlia approved these changes

2023-07-25 14:44 UTC, merged