Add Metric Store Group as contributers
cloudfoundry/community pull request #647
Opened 2023-07-13 15:05 UTC by jbooherl

We have been maintaining the metric store release and believe that we meet criteria based on support interactions in  #op-apps-assist-tas-metric-store

2023-07-17 17:13 UTC, jbooherl commented on toc/working-groups/app-runtime-platform.md
> +  - `
Whoops. Updated and force pushed. I added the repo to the metric-store groups so we can archive it

2023-07-17 17:14 UTC, jbooherl commented on toc/working-groups/app-runtime-platform.md
> +  - cloudfoundry/metric-store-ci
Removed the repos from the Metrics and Logging teams.

2023-07-17 17:15 UTC, jbooherl commented on toc/working-groups/app-runtime-platform.md
> +    github: svcboteos
Done

2023-07-17 17:20 UTC, jbooherl commented on toc/working-groups/app-runtime-platform.md
> +    github: jbooherl
Done! https://github.com/cloudfoundry/community/pull/650

2023-07-17 17:50 UTC, jbooherl commented
> It is my understanding that this will make the working group yaml match the state of the world and that these contributors have been working on these projects for a long time. However, I am less familiar with this group and want to make sure that everyone meets the same standard for approver as described [here](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#approver). Please provide details about how long each person has been working on these projects and links to their contributions.

I have been working as the tech lead on the project since September of 2022. 
Metric Store is being maintained but there have not been a lot of sweeping changes. It is used as the backend for App Metrics which is still in use by customers and we do regular tile releases of the product.
Hovhannes is the anchor of the project. I believe his support ticket work in #op-apps-assist-tas-metric-store and possibly PRs qualify him. 
Gevorg has also been supporting metric store and making changes to the [metric store repo](https://github.com/cloudfoundry/metric-store-release/commits?author=gggevorgyan)
Meri has just returned from parental leave and prior to that also committed to [metric store](https://github.com/cloudfoundry/metric-store-release/commits?author=myeghiazarya)
> 
> Here are several examples of people showing their work to apply as an approver
> 
> * [An example of the easiest way to link commits. ](https://github.com/cloudfoundry/community/pull/644)
> * [ An example of a more thorough list](https://github.com/cloudfoundry/community/pull/628)
> 
> ❓ @Benjamintf1 - This PR will be adding ownership to the metric-store repos, which are currently in your area. Does this split make sense to you?

2023-07-18 12:40 UTC, stephanme requested changes

2023-07-18 12:40 UTC, stephanme commented on toc/working-groups/app-runtime-platform.md
> +    github: svcboteos
Bots should be added as bots and not as approvers. Bots can be configured on WG level and on WG area level.
Bots don't need to be added as contributors. All bots (and approvers, reviewers, leads) get added to the cloudfoundry org automatically.

See [rfc-0014-github-teams-and-access.md](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0014-github-teams-and-access.md) for the possible teams and permissions. 
The [Service Management WG](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/service-management.md) contains examples for WG bot and WG area bot configuration.

2023-07-18 21:20 UTC, jbooherl commented on toc/working-groups/app-runtime-platform.md
> +    github: svcboteos
Moved the bot to the upper WG section

2023-07-18 21:43 UTC, Benjamintf1 commented
@ameowlia yeah, we havn't really been ever maintaining the metric-store repos.

2023-07-19 14:33 UTC, ameowlia commented on toc/working-groups/app-runtime-platform.md
> +    github: svcboteos
Oops! Good catch @stephanme. I didn't realize it was a bot 🤦‍♀️

2023-07-19 14:34 UTC, ameowlia approved these changes

2023-07-19 14:35 UTC, merged