RFC - deprecate metrics agent
cloudfoundry/community pull request #682
Opened 2023-09-12 21:42 UTC by mkocher

We don't think anyone is using this and want to deprecate it. See RFC for details.

2023-09-19 14:49 UTC, ameowlia approved these changes

2023-09-19 14:52 UTC, beyhan commented
Are there any docs which need to be updated because of the removal of the `Metrics Agent`?

2023-09-19 14:52 UTC, ameowlia requested changes

2023-09-19 14:52 UTC, ameowlia commented on toc/rfc/rfc-0021-deprecate-metrics-agent.md
> +- In Three Months - Stop cutting new releases of metrics agent
```suggestion
- Today - Mark [metrics-discovery-release](https://github.com/cloudfoundry/metrics-discovery-release) repo as deprecated
- In One Month
   * Accept a PR to move metrics-agent to an ops file in CF-deployment, if a community member needs Metrics Agent and would like a ops file.
   * Remove metrics agent from cf-deployment
- In Three Months - Stop cutting new releases of metrics agent
```

Editing to show that the opsfile should exist already when the metrics agent is removed from cf-deployment.

2023-09-19 17:17 UTC, mkocher commented
Thank you for the feedback. Merged @ameowlia's suggestion and added a step to make sure we clean up the docs. (thanks @beyhan). Is this ready to go?

2023-09-20 11:34 UTC, beyhan commented
@mkocher thanks for the updates! Yes, we discussed that we can start the [Final Comment Period](https://github.com/cloudfoundry/community/tree/main/toc/rfc#final-comment-period) next Tuesday. I also asked around at SAP whether this could cause an issue but looks good for now.

2023-10-10 14:51 UTC, beyhan commented
The [Final Comment Period](https://github.com/cloudfoundry/community/tree/main/toc/rfc#final-comment-period) starts and if there are no major changes we are going to approve this next Tuesday 17th of October

2023-10-17 14:42 UTC, ChrisMcGowan approved these changes

2023-10-17 14:43 UTC, rkoster approved these changes

2023-10-17 14:43 UTC, ameowlia approved these changes

2023-10-17 14:43 UTC, merged