Add roles yaml section to Vulnerability Management WG
cloudfoundry/community pull request #746
Opened 2024-01-10 09:08 UTC by beyhan

This is need for the inactive user automation to not suggest users for deletion who has roles

2024-01-10 20:45 UTC, paulcwarren commented on toc/working-groups/vulnerability-management.md
> +- name: Mathias Essenpreis
No longer active

2024-01-10 20:46 UTC, paulcwarren commented on toc/working-groups/vulnerability-management.md
> +- name: Prateek Mehrotra
No longer active

2024-01-10 20:46 UTC, paulcwarren approved these changes

2024-01-10 20:46 UTC, paulcwarren requested changes
Can we remove the inactive users please?

2024-01-11 07:24 UTC, beyhan commented on toc/working-groups/vulnerability-management.md
> +- name: Mathias Essenpreis
Done

2024-01-11 07:24 UTC, beyhan commented on toc/working-groups/vulnerability-management.md
> +- name: Prateek Mehrotra
Done

2024-01-11 16:05 UTC, beyhan commented
I'm going to merge this because org automation wasn't in place and no roles were given to the removed people.

2024-01-11 16:14 UTC, ameowlia approved these changes

2024-01-11 16:29 UTC, merged