Adding MultiApps bot
cloudfoundry/community pull request #885
Opened 2024-06-07 12:08 UTC by ikasarov

Adding a new bot github account for use with release/branch restrictions

2024-06-10 07:51 UTC, beyhan commented
Hi @ikasarov,

two approvers of the MultiApps area need to approve this pr or put thumps up on it before merging.

2024-06-10 08:04 UTC, stephanme requested changes

2024-06-11 07:28 UTC, boyan-velinov approved these changes

2024-06-11 08:08 UTC, theghost5800 approved these changes

2024-06-11 08:10 UTC, s-yonkov-yonkov approved these changes

2024-06-11 12:19 UTC, ikasarov commented on org/contributors.yml
> +- cf-mta-deploy-bot
removed it

2024-06-14 08:53 UTC, stephanme approved these changes

2024-06-14 08:53 UTC, merged