Add Yusmen Zabanov as a member of the cloudfoundry org
cloudfoundry/community pull request #931
Opened 2024-07-23 14:24 UTC by georgethebeatle

Yusmen is a colleague from SAP who is joining the cf-on-k8s working group

2024-07-23 15:07 UTC, beyhan requested changes
I don't find `yusmen-zabanov_sap` as user and https://github.com/yusmen-zabanov_sap returns 404.

2024-07-24 10:10 UTC, georgethebeatle commented
Fair point @beyhan 

I have provided the [proper user](https://github.com/zabanov-lab) now, sorry for the confusion

2024-07-24 11:35 UTC, beyhan commented
According to  https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-and-revocation
>Two existing Contributors, Reviewers, or Approvers must attest that they meet the criteria by reviewing the PR.

When the above is fulfilled you can merge the pr.

2024-07-25 08:25 UTC, danail-branekov approved these changes

2024-07-26 14:32 UTC, christopherclark approved these changes

2024-07-26 17:50 UTC, davewalter approved these changes

2024-07-29 06:53 UTC, beyhan approved these changes

2024-07-29 09:34 UTC, merged