Add homebrew-tap to Admin WG
cloudfoundry/community pull request #967
Opened 2024-09-05 19:22 UTC by gururajsh

Since CF CLI uses homebrew-tap repository is used by teams across multiple WGs, moving it to Admin WG. Related PR https://github.com/cloudfoundry/community/pull/944.

Have included some of the current CLI approvers as approvers for this.

2024-09-06 06:41 UTC, beyhan commented
FYI (current approvers of `cloudfoundry/homebrew-tap`) @aramprice ,@ystros ,@selzoc ,@dlresende ,@totherme ,@blgm ,@ifindlay-cci ,@klakin-pivotal, @nouseforaname ,@jhvhs ,@lnguyen ,@ragaskar the `cloudfoundry/homebrew-tap` repository will be moved with this pr from the FI WG to the shared area in the Admin WG as discussed in https://github.com/cloudfoundry/community/pull/944. Pls comment on this pr if you still want to be an approver.

2024-09-06 06:44 UTC, beyhan requested changes
@gururajsh could you please also remove the repository from FI WG with this pr. Maybe we can change the title of the pr to move instead of add.

2024-09-06 14:06 UTC, gururajsh commented
> @gururajsh could you please also remove the repository from FI WG with this pr. Maybe we can change the title of the pr to move instead of add.

Done.

2024-09-06 14:51 UTC, beyhan approved these changes

2024-09-06 15:41 UTC, aramprice commented
@beyhan - does this mean that the Admin WG will be responsible for publishing / approving new versions of `bosh-cli`, `bbr` and `bbl` formulae?

2024-09-09 08:12 UTC, beyhan commented
> @beyhan - does this mean that the Admin WG will be responsible for publishing / approving new versions of `bosh-cli`, `bbr` and `bbl` formulae?

@aramprice  The approves of the area will be responsible. Admin WG is just a location we thought which is good for repositories which need to be shared across WGs.

2024-09-09 13:35 UTC, lnguyen approved these changes

2024-09-09 16:04 UTC, jpalermo commented
Yeah, the bosh-cli pipelines won't break with this move since we use a deploy key in the pipeline to update the tap. So we don't really need anybody involved with this area to continue as we are now. Is that fine?

2024-09-10 12:47 UTC, ChrisMcGowan approved these changes

2024-09-10 14:18 UTC, ameowlia requested changes
This removes all approvers from the Foundational Infrastructure working group. Now there are only approvers from the App Runtime Interfaces working group.

❓ Is this intended?

If this is the desired outcome and it doesn't need to be shared between groups then it doesn't need to live in the Admin WG.

2024-09-10 14:34 UTC, rkoster approved these changes

2024-09-10 14:51 UTC, ameowlia commented on toc/ADMIN.md
> +- name: Shared
```suggestion
- name: Homebrew
```

2024-09-10 14:51 UTC, ameowlia commented on toc/ADMIN.md
> +- name: Shared
Let's make this less generic.

2024-09-10 14:52 UTC, rkoster requested changes

2024-09-16 15:05 UTC, gururajsh commented on toc/ADMIN.md
> +- name: Shared
Done

2024-09-16 15:05 UTC, gururajsh commented on toc/ADMIN.md
> +  approvers:
Done

2024-09-17 14:44 UTC, rkoster approved these changes

2024-09-17 14:44 UTC, ChrisMcGowan approved these changes

2024-09-17 14:45 UTC, stephanme approved these changes

2024-09-17 14:45 UTC, merged